# Generated by Django 2.2 on 2019-04-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_list_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date_time',
            field=models.CharField(max_length=200),
        ),
    ]
